- name: Configurar servidor web
  hosts: all
  become: yes
  tasks:
    - name: Instalar Apache
      yum:
        name: httpd
        state: present

    - name: Copiar archivo HTML
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Reiniciar Apache
      service:
        name: httpd
        state: restarted
